# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/ocean/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/ocean/proprietary/etc/motorola/sysconfig/dtv-hidepackages.xml:system/etc/motorola/sysconfig/dtv-hidepackages.xml \
    vendor/motorola/ocean/proprietary/etc/permissions/com.motorola.hardware.dtv.xml:system/etc/permissions/com.motorola.hardware.dtv.xml \
    vendor/motorola/ocean/proprietary/etc/permissions/mot_dtv_permissions.xml:system/etc/permissions/mot_dtv_permissions.xml \
    vendor/motorola/ocean/proprietary/etc/permissions/unavail.com.motorola.hardware.dtv.xml:system/etc/permissions/unavail.com.motorola.hardware.dtv.xml \
    vendor/motorola/ocean/proprietary/lib/android.hardware.tv.cec@1.0.so:system/lib/android.hardware.tv.cec@1.0.so \
    vendor/motorola/ocean/proprietary/lib/android.hardware.tv.input@1.0.so:system/lib/android.hardware.tv.input@1.0.so \
    vendor/motorola/ocean/proprietary/lib/libdtvtuner.so:system/lib/libdtvtuner.so \
    vendor/motorola/ocean/proprietary/lib/motorola.hardware.tv@1.0.so:system/lib/motorola.hardware.tv@1.0.so \
    vendor/motorola/ocean/proprietary/lib/vndk-28/android.hardware.tv.cec@1.0.so:system/lib/vndk-28/android.hardware.tv.cec@1.0.so \
    vendor/motorola/ocean/proprietary/lib/vndk-28/android.hardware.tv.input@1.0.so:system/lib/vndk-28/android.hardware.tv.input@1.0.so \
    vendor/motorola/ocean/proprietary/lib64/android.hardware.tv.cec@1.0.so:system/lib64/android.hardware.tv.cec@1.0.so \
    vendor/motorola/ocean/proprietary/lib64/android.hardware.tv.input@1.0.so:system/lib64/android.hardware.tv.input@1.0.so \
    vendor/motorola/ocean/proprietary/lib64/libdtvtuner.so:system/lib64/libdtvtuner.so \
    vendor/motorola/ocean/proprietary/lib64/motorola.hardware.tv@1.0.so:system/lib64/motorola.hardware.tv@1.0.so \
    vendor/motorola/ocean/proprietary/lib64/vndk-28/android.hardware.tv.cec@1.0.so:system/lib64/vndk-28/android.hardware.tv.cec@1.0.so \
    vendor/motorola/ocean/proprietary/lib64/vndk-28/android.hardware.tv.input@1.0.so:system/lib64/vndk-28/android.hardware.tv.input@1.0.so \
    vendor/motorola/ocean/proprietary/vendor/bin/hw/motorola.hardware.tv@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.tv@1.0-service \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Bluetooth_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/General_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Global_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Handset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Hdmi_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Headset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Speaker_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Bluetooth_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/General_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Global_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Handset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Hdmi_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Headset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Speaker_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/init/motorola.hardware.tv@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.tv@1.0-service.rc \
    vendor/motorola/ocean/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_csot_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_csot_720p_622.xml \
    vendor/motorola/ocean/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_ofilm_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_ofilm_720p_622.xml \
    vendor/motorola/ocean/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_720p_622.xml \
    vendor/motorola/ocean/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/motorola/ocean/proprietary/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8006U_Pramboot.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/aw8624_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/focaltech-ofilm-ft8006u-0e-001-ocean.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ofilm-ft8006u-0e-001-ocean.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/ilitek-tianma-ILI9881-1c-69-ocean.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek-tianma-ILI9881-1c-69-ocean.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/mono.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/mono.cnt \
    vendor/motorola/ocean/proprietary/vendor/firmware/novatek_ts-csot-NT36672A-180919-07-ocean.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-csot-NT36672A-180919-07-ocean.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/motorola/ocean/proprietary/vendor/lib/hw/motorola.hardware.tv@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/motorola.hardware.tv@1.0-impl.so \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/abov_sar.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/abov_sar.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_adsp_loader.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_adsp_loader.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_analog_cdc.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_analog_cdc.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_apr.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_apr.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_cpe_lsm.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_cpe_lsm.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_digital_cdc.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_digital_cdc.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_hdmi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_hdmi.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_machine_ext_sdm450.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_machine_ext_sdm450.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_machine_sdm450.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_machine_sdm450.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_mbhc.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_mbhc.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_native.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_native.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_pinctrl_wcd.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_pinctrl_wcd.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_platform.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_platform.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_q6.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_q6.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_q6_notifier.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_q6_notifier.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_stub.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_stub.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_swr.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_swr.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_swr_ctrl.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_swr_ctrl.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_usf.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_usf.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_wcd9335.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_wcd9335.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_wcd9xxx.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_wcd9xxx.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_wcd_core.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_wcd_core.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_wcd_cpe.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_wcd_cpe.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_wsa881x.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_wsa881x.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/audio_wsa881x_analog.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/audio_wsa881x_analog.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/aw8624.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/aw8624.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/drv2624_mmi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/drv2624_mmi.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/exfat.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/exfat.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/focaltech_mmi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/focaltech_mmi.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/ilitek_mmi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/ilitek_mmi.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/isdbt.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/isdbt.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/mcDrvModule.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mcDrvModule.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/mmi_annotate.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mmi_annotate.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/mmi_info.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mmi_info.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/mmi_sys_temp.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mmi_sys_temp.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.alias \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.dep \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/moto_f_usbnet.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/moto_f_usbnet.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/mpq-adapter.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mpq-adapter.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/mpq-dmx-hw-plugin.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/mpq-dmx-hw-plugin.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/nova_mmi.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/nova_mmi.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/sensors_class.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/sensors_class.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/snd_soc_tfa9874.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/snd_soc_tfa9874.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/st21nfc.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/st21nfc.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/sx932x_sar.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/sx932x_sar.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/tps61280.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/tps61280.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/tzlog_dump.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/tzlog_dump.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/utags.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/utags.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/watchdog_cpu_ctx.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/watchdog_cpu_ctx.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/modules/watchdogtest.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/watchdogtest.ko \
    vendor/motorola/ocean/proprietary/vendor/lib/motorola.hardware.tv@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/motorola.hardware.tv@1.0.so \
    vendor/motorola/ocean/proprietary/vendor/lib64/hw/motorola.hardware.tv@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/motorola.hardware.tv@1.0-impl.so \
    vendor/motorola/ocean/proprietary/vendor/lib64/motorola.hardware.tv@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.tv@1.0.so
